import { Platform, StyleSheet } from "react-native";

export const detailsAnimeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0D0D0D",
  },
  headerSafeArea: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  animatedHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  headerBlur: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 48,
    paddingBottom: 12,
    backgroundColor: "#0D0D0D",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  headerBackButton: {
    marginRight: 12,
    padding: 4,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontFamily: "Genjiro",
    color: "#fff",
    letterSpacing: 3,
  },
  scrollView: {
    flex: 1,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    fontFamily: "Agdasima",
    color: "#ff6b6b",
    textAlign: "center",
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: "#A78BFA",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    borderCurve: "continuous",
  },
  retryText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Agdasima",
    fontWeight: "600",
  },
  noDataText: {
    fontSize: 14,
    fontFamily: "Agdasima",
    color: "#999",
    textAlign: "center",
    paddingVertical: 20,
  },
  backgroundShapes: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 400,
    overflow: "hidden",
  },
  blobShape1: {
    position: "absolute",
    top: -48,
    right: -80,
    width: 304,
    height: 304,
    backgroundColor: "#7C3AED",
    borderRadius: 152,
    borderCurve: "continuous",
    opacity: 0.15,
    transform: [{ scaleX: 1.5 }, { rotate: "25deg" }],
  },
  blobShape2: {
    position: "absolute",
    top: 96,
    left: -96,
    width: 248,
    height: 248,
    backgroundColor: "#A78BFA",
    borderRadius: 124,
    borderCurve: "continuous",
    opacity: 0.1,
    transform: [{ scaleY: 1.3 }, { rotate: "-15deg" }],
  },
  blobShape3: {
    position: "absolute",
    top: 200,
    right: 48,
    width: 200,
    height: 200,
    backgroundColor: "#C4B5FD",
    borderRadius: 100,
    borderCurve: "continuous",
    opacity: 0.08,
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 10,
    width: 36,
    height: 36,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  heroSection: {
    position: "relative",
    width: "100%",
    aspectRatio: 16 / 9,
    marginBottom: -60,
    overflow: "hidden",
    backgroundColor: "#000",
  },
  backdropImage: {
    width: "100%",
    height: "100%",
  },
  descriptionSectionNative: {
    marginHorizontal: 20,
    borderRadius: 12,
    borderCurve: "continuous",
    padding: 20,
    marginBottom: 20,
    zIndex: 5,
    position: "relative",
    overflow: "hidden",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.3)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0.5)",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(0, 0, 0, 0.3)",
    borderRightWidth: 1,
    borderRightColor: "rgba(0, 0, 0, 0.3)",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  titleYearRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    flexWrap: "wrap",
  },
  mainTitle: {
    fontSize: 16,
    letterSpacing: 2,
    fontFamily: "Genjiro",
    color: "#FFFFFF",
    flex: 1,
    marginRight: 12,
  },
  year: {
    fontSize: 16,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#fff",
    flexShrink: 0,
  },
  subtitleText: {
    fontSize: 14,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#fff",
    opacity: 0.9,
    marginBottom: 8,
  },
  studioInfo: {
    fontSize: 16,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#C4B5FD",
    marginBottom: 12,
  },
  description: {
    fontSize: 16,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#FFFFFF",
    lineHeight: 20,
    marginBottom: 8,
  },
  expandDescriptionText: {
    fontSize: 14,
    fontFamily: "Agdasima",
    color: "#C4B5FD",
    fontWeight: "600",
    marginBottom: 15,
  },
  episodeStatusRow: {
    gap: 5,
  },
  episodeCount: {
    fontSize: 16,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    fontWeight: "500",
    color: "#fff",
  },
  status: {
    fontSize: 16,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  statsSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 24,
    gap: 10,
  },
  statusSection: {
    marginHorizontal: 20,
    marginBottom: 24,
  },
  statusSectionLabel: {
    fontSize: 12,
    fontFamily: "Agdasima",
    letterSpacing: 2,
    color: "#999",
    fontWeight: "600",
    marginBottom: 12,
  },
  genreCrewSectionNative: {
    marginHorizontal: 20,
    borderRadius: 12,
    borderCurve: "continuous",
    padding: 20,
    marginBottom: 24,
    overflow: "hidden",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.3)",
    borderBottomWidth: 2,
    borderBottomColor: "rgba(0, 0, 0, 0.5)",
    borderLeftWidth: 2,
    borderLeftColor: "rgba(0, 0, 0, 0.3)",
    borderRightWidth: 2,
    borderRightColor: "rgba(0, 0, 0, 0.3)",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  genreRow: {
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 16,
    letterSpacing: 1,
    fontWeight: "bold",
    fontFamily: "Agdasima",
    color: "#C4B5FD",
    marginBottom: 10,
  },
  genreList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  crewList: {
    gap: 8,
  },
  reviewsSectionNative: {
    marginHorizontal: 20,
    borderRadius: 12,
    borderCurve: "continuous",
    padding: 20,
    marginBottom: 24,
    overflow: "hidden",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.3)",
    borderBottomWidth: 2,
    borderBottomColor: "rgba(0, 0, 0, 0.5)",
    borderLeftWidth: 2,
    borderLeftColor: "rgba(0, 0, 0, 0.3)",
    borderRightWidth: 2,
    borderRightColor: "rgba(0, 0, 0, 0.3)",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  reviewsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  addReviewButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
  },
  relatedSection: {
    marginBottom: 32,
  },
  relatedScrollContent: {
    paddingHorizontal: 20,
    gap: 12,
  },
  relatedCard: {
    width: 120,
    height: 170,
    borderRadius: 8,
    borderCurve: "continuous",
    overflow: "hidden",
    backgroundColor: "#252525",
  },
  relatedCardPressed: {
    opacity: 0.7,
  },
  relatedCardImage: {
    width: "100%",
    height: "100%",
  },
  relatedCardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 8,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  relatedCardTitle: {
    fontSize: 12,
    fontFamily: "Agdasima",
    color: "#fff",
    fontWeight: "600",
  },
  expandButton: {
    paddingVertical: 8,
    alignItems: "center",
    marginTop: 5,
  },
  expandButtonText: {
    fontSize: 12,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#666",
    fontWeight: "500",
  },
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
  },
  paginationButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderCurve: "continuous",
    backgroundColor: "rgba(167, 139, 250, 0.2)",
    gap: 5,
  },
  paginationButtonDisabled: {
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    opacity: 0.5,
  },
  paginationButtonText: {
    fontSize: 14,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#fff",
    fontWeight: "500",
  },
  paginationButtonTextDisabled: {
    color: "#666",
  },
  pageIndicator: {
    fontSize: 14,
    fontFamily: "Agdasima",
    letterSpacing: 0.5,
    color: "#fff",
    fontWeight: "500",
  },
});

